#!/bin/bash

# Create shared files /usr/local/etc/
# These are (by default) source by users `root` and `docker`
# in $HOME/.local_profile and $HOME/.local_env respectively
# 
# The .local_env and .local_profile file inside each users
# home directories are always unique to the user. They may
# use the ones created below if they don't exist, then
# symlink them the their $HOME. Or source them. Either
# way, both files are unique to each image/container and
# that's the place to customize your configuretion. The reason
# they exist lies in the fact that:
#
#   1. zsh uses .zprofile, and never .profile
#   2. same goes for .bashrc vs .zshrc
# 
# But, normally, you'd want the same environment in both zsh anb bash shells.
# The idea is that you USE zsh, but all scripts are written in bash.
#
touch /usr/local/etc/.local_profile
touch /usr/local/etc/.local_env

cd $HOME
rm -f .profile              && ln -s /usr/local/share/host_provided/dotfiles/.profile
rm -f .zprofile             && ln -s /usr/local/share/host_provided/dotfiles/.zprofile
rm -f .bashrc               && ln -s /usr/local/share/host_provided/dotfiles/.bashrc
rm -f .zshrc                && ln -s /usr/local/share/host_provided/dotfiles/.zshrc
rm -f .vimrc                && ln -s /usr/local/share/host_provided/dotfiles/.vimrc
rm -f .inputrc              && ln -s /usr/local/share/host_provided/dotfiles/.inputrc
rm -f .shared_shell_env     && ln -s /usr/local/share/host_provided/dotfiles/.shared_shell_env
rm -f .shared_shell_profile && ln -s /usr/local/share/host_provided/dotfiles/.shared_shell_profile
rm -rf .vim                 && ln -s /usr/local/share/host_provided/dotfiles/.vim
rm -rf .zsh                 && ln -s /usr/local/share/host_provided/dotfiles/.zsh
rm -rf .oh-my-zsh           && ln -s /usr/local/share/host_provided/dotfiles/.oh-my-zsh
